CREATE TABLE IF NOT EXISTS `keys` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `public` VARCHAR(64) NOT NULL,
  `private` VARCHAR(1024) NOT NULL,
  `symbol` VARCHAR(64) NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `store_id` INT NOT NULL DEFAULT 1,
  UNIQUE KEY `uq_keys_public` (`public`)
);

CREATE TABLE IF NOT EXISTS settings (
  `name` VARCHAR(255) NOT NULL,
  `value` VARCHAR(1024),
  UNIQUE(`name`)
);
CREATE TABLE IF NOT EXISTS `tron_balances` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `account` VARCHAR(64) NOT NULL,
  `symbol` VARCHAR(64) NOT NULL,
  `balance` DECIMAL(52, 18) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_tron_balances_account_symbol` (`account`, `symbol`)
);