CREATE TABLE IF NOT EXISTS `keys` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `public` VARCHAR(64) NOT NULL,
  `private` VARCHAR(1024) NOT NULL,
  `symbol` VARCHAR(64) NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `store_id` INT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS settings (
  `name` VARCHAR(255) NOT NULL,
  `value` VARCHAR(1024),
  UNIQUE(`name`)
);